# ソースファイル：アルファベット順にソート
SOURCES = \
	announcecurrentaction.c \
	armattack.c \
	common.c \
	decideaction.c \
	ev3module.c \
	exeaction.c \
	exeattack.c \
	getinputsensor.c \
	getstopkey.c \
	getTimeLeft.c \
	main.c \
	movecenterring.c \
	moveToEnemy.c \
	startsystem.c

# ビルド生成物（実行ファイル）の名前
TARGET = sumo

# config? おそらくLinuxのライブラリを追加しているのかも
CONF = Linux

# アーキテクチャ、mindstormのもの
ARCH = AM1808

# ビルドルール：このパスを間違えるとビルド失敗する
include ../../open_first/rules.mk

