SOURCES = main.c \
	armattack.c \
	ev3module.c \
	startsystem.c \
	common.c \
	getinputsensor.c \
	decideaction.c \
	getstopkey.c \
	getTimeLeft.c \
	announcecurrentaction.c

TARGET = sumo
CONF = Linux
ARCH = AM1808
include ../../open_first/rules.mk

